document.write("<!--<a href='#home'>Home</a>-->");
document.write("<a href='index.html'>Home</a>");
document.write("<a class='active' href='admin.html'>Admin</a>");
document.write("<div class='dropdown'>");
document.write("<button class='dropbtn'>Employees <i class='fa fa-caret-down'></i></button>");
document.write("<div class='dropdown-content'>");
document.write("<a href='#addemployee'>Add Employee</a>");
document.write("<a href='#editemployee'>Edit Employee</a>");
document.write("<a href='#rememployee'>Remove Employee</a>");
document.write("<a href='#addjob'>Add Occupation</a>");
document.write("<a href='#editjob'>Edit Occupation</a>");
document.write("<a href='#remjob'>Remove Occupation</a>");
document.write("<a href='' onclick=alert(\'No need to do this, Dirk is already awesome\')>Add Awesome Employees</a>");
document.write("</div>");
document.write("</div>");
document.write("<div class='dropdown'>");
document.write("<button class='dropbtn'>Machines <i class='fa fa-caret-down'></i></button>");
document.write("<div class='dropdown-content'>");
document.write("<a href='#bring'>Add Machine</a>");
document.write("<a href='#deliver'>Edit Machine</a>");
document.write("<a href='#package'>Remove Machine</a>");
document.write("<a href='#'>Remove Machine</a>");
document.write("<a href='#'>Remove Machine</a>");
document.write("<a href='#'>Remove Machine</a>");
document.write("</div>");
document.write("</div>");
document.write("<div class='dropdown'>");
document.write("<button class='dropbtn'>Working Places <i class='fa fa-caret-down'></i></button>");
document.write("<div class='dropdown-content'>");
document.write("<a href='workingplace.html'>View Working Place</a>");
document.write("<a href='#addsect'>Add Section</a>");
document.write("<a href='#editsect'>Edit Section</a>");
document.write("<a href='#remsect'>Remove Section</a>");
document.write("<a href='#addpan'>Add Panel</a>");
document.write("<a href='#edtpan'>Edit Panel</a>");
document.write("<a href='#rempan'>Remove Panel</a>");
document.write("</div>");
document.write("</div>");
document.write("<div class='dropdown'>");
document.write("<button class='dropbtn'>Reports <i class='fa fa-caret-down'></i></button>");
document.write("<div class='dropdown-content'>");
document.write("<a href='#viewrep'>View Reports</a>");
document.write("<a href='#editrep'>Edit Reports</a>");
document.write("<a href='#printrep'>Print Reports</a>");
document.write("<a href='#mailrep'>E-Mail Reports</a>");
document.write("<a href='#'>Remove Machine</a>");
document.write("<a href='#'>Remove Machine</a>");
document.write("</div>");
document.write("</div>");